version: '3'
services:
  mongodb:
    image: mongodb/mongodb-community-server:6.0-ubi8
    command: mongod --bind_ip_all
    container_name: mongodb
    restart: always
    network_mode: bridge
  api:
    image: registry.gitlab.com/madee.tech/registry/lab-lineoa-express:latest
    container_name: lab-lineoa-express-api
    restart: always
    ports:
      - "3000:3001"
    environment:
      - DB=mongodb://mongodb:27017/node-api-101
      - PAI=https://rpi.praram9.com:8088/dev/patient/test
    logging:
          driver: "json-file"
          options:
            max-file: '3'
            max-size: '500m'
    links:
      - mongodb
    network_mode: bridge